name:Build and Deploy
on:
 push:
    branches:
      -main
jobs:
 build-and-deploy:
    runs-on:ubuntu-latest
    concurrency:ci-s((github.ref))
    steps:
      -name:Checkout
        uses:actions/checkout@v2
       -name:Configure Node
        uses:actions/setup-node@vi
        with:
          node-version:12.18.4'
        name:Install
        run:|
          прис
          npm run build
        name:Deploy
        uses:JamesIves/github-pages-deploy-action@vi
        with:
          folders build
          branch:gh-pages
